### ISSUE TITLE
hub.tools.conf.integrate doesn't take list as 1st arg

### ISSUE THREAD

**Issue by smokeytheblair** [saltstack/pop#34] opened 2019-06-25 15:32 UTC
**Expected**:
hub.tools.conf.integrate(['poppy'], loader='yaml', roots=True)

**Actual**:
hub.tools.conf.integrate('poppy', loader='yaml', roots=True)

The `integrate` call does not throw or traceback.  It simply fails to load the config.

**Comment by thatch45** [comment] 2019-08-30 15:21
I can't reproduce this and the code is in place to handle it so I am going to close it out

**Closed** 2019-08-30 16:55 UTC
Labels: bug
